# Generated by Django 3.2.14 on 2022-08-29 10:12

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('content', ckeditor.fields.RichTextField(verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('status', models.SmallIntegerField(choices=[(1, '已发表'), (2, '草稿箱')], verbose_name='状态')),
                ('publlic', models.BooleanField(verbose_name='是否公开')),
                ('love_num', models.IntegerField(verbose_name='收藏量')),
                ('read_num', models.IntegerField(verbose_name='阅读量')),
                ('ip', models.CharField(blank=True, max_length=30, null=True, verbose_name='ip属地')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('password', models.CharField(max_length=40, verbose_name='密码')),
                ('email', models.EmailField(max_length=40, verbose_name='邮箱')),
                ('detail', models.CharField(blank=True, max_length=256, null=True, verbose_name='详细信息')),
                ('touxiang', models.ImageField(blank=True, max_length=64, null=True, upload_to='touxiang', verbose_name='头像')),
                ('ip', models.CharField(blank=True, max_length=30, null=True, verbose_name='ip属地')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('latest_edit', models.DateTimeField(auto_now=True, verbose_name='最近编辑时间')),
            ],
        ),
        migrations.CreateModel(
            name='SecondComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300, verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_comment_receiver', to='article.user', verbose_name='接收者')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_comment_sender', to='article.user', verbose_name='发送者')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=256, verbose_name='内容')),
                ('read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_receiver', to='article.user', verbose_name='收信人')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_sender', to='article.user', verbose_name='收信人')),
            ],
        ),
        migrations.CreateModel(
            name='FirstComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300, verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.article', verbose_name='对应文章')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.user', verbose_name='发送者')),
            ],
        ),
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.article', verbose_name='博客')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.user', verbose_name='用户')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.user', verbose_name='作者'),
        ),
    ]
