# Generated by Django 3.2.14 on 2022-09-02 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='nid',
            field=models.CharField(default=202209011245, max_length=15, verbose_name='编号'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='love_num',
            field=models.IntegerField(default=0, verbose_name='收藏量'),
        ),
        migrations.AlterField(
            model_name='article',
            name='read_num',
            field=models.IntegerField(default=0, verbose_name='阅读量'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '立即发表'), (2, '暂时存进草稿箱')], verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='user',
            name='touxiang',
            field=models.ImageField(blank=True, default='touxiang/user.png', max_length=64, null=True, upload_to='touxiang', verbose_name='头像'),
        ),
    ]
