# Generated by Django 3.2.14 on 2022-09-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20220902_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='display',
            field=models.BooleanField(default=True, verbose_name='是否可见'),
        ),
    ]
