# Generated by Django 3.2.14 on 2022-09-04 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_alter_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=18, verbose_name='用户名'),
        ),
        migrations.CreateModel(
            name='Attention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attention_guest', to='article.user', verbose_name='粉丝')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrention_host', to='article.user', verbose_name='博主')),
            ],
        ),
    ]
