# Generated by Django 3.2.14 on 2022-09-04 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20220904_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='love_num',
        ),
    ]
