# Generated by Django 3.2.14 on 2022-09-10 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_remove_article_love_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='attention_remain',
            field=models.BooleanField(default=True, verbose_name='我被关注时开通邮箱提醒'),
        ),
        migrations.AddField(
            model_name='user',
            name='love_remain',
            field=models.BooleanField(default=True, verbose_name='我的博客被收藏时开通邮箱提醒'),
        ),
        migrations.AddField(
            model_name='user',
            name='message_remain',
            field=models.BooleanField(default=True, verbose_name='我的博客收到评论时开通邮箱提醒'),
        ),
        migrations.AddField(
            model_name='user',
            name='new_article_remain',
            field=models.BooleanField(default=True, verbose_name='我关注的博主有新作品时开通邮箱提醒'),
        ),
    ]
