# Generated by Django 3.2.14 on 2022-09-17 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20220917_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secondcomment',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='secondcomment',
            name='sender',
        ),
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.CharField(default='这是评论的示范内容', max_length=255, verbose_name='评论内容'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='article.article', verbose_name='评论的文章'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='reply_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replyers', to='article.user', verbose_name='评论接收者'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senders', to='article.user', verbose_name='评论发布者'),
        ),
        migrations.DeleteModel(
            name='FirstComment',
        ),
        migrations.DeleteModel(
            name='SecondComment',
        ),
    ]
