# Generated by Django 3.2.14 on 2022-09-18 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_genre_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.comment', verbose_name='回复的评论'),
        ),
    ]
