# Generated by Django 3.2.14 on 2022-09-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_message_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='标题')),
                ('link', models.CharField(max_length=255, verbose_name='链接')),
                ('kind', models.SmallIntegerField(choices=[(1, '站长推荐'), (2, '热门看点'), (3, '知识分享')], verbose_name='分类')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='message_remain',
            field=models.BooleanField(default=True, verbose_name='我的博客收到评论,或有人回复我的评论时开通邮箱提醒'),
        ),
        migrations.AlterField(
            model_name='user',
            name='new_article_remain',
            field=models.BooleanField(default=True, verbose_name='我关注的博主发布新作品时开通邮箱提醒'),
        ),
    ]
