# Generated by Django 3.2.14 on 2022-09-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0014_auto_20220919_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='资源名称')),
                ('src', models.FileField(max_length=128, upload_to='resources/%Y/%m/%d', verbose_name='文件')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(max_length=60, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='user',
            name='touxiang',
            field=models.ImageField(blank=True, default='touxiang/user.png', max_length=64, null=True, upload_to='touxiang/%Y/%m/%d', verbose_name='头像'),
        ),
    ]
