# Generated by Django 3.2.14 on 2022-09-25 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0015_auto_20220922_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(max_length=64, upload_to='photos/%Y/%m/%d', verbose_name='图片')),
                ('title', models.CharField(max_length=32, verbose_name='名称')),
            ],
        ),
        migrations.AlterField(
            model_name='link',
            name='kind',
            field=models.SmallIntegerField(choices=[(1, '精彩推荐'), (2, '热门看点'), (3, '知识分享')], verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='src',
            field=models.FileField(max_length=128, upload_to='resources/%Y/%m', verbose_name='文件'),
        ),
        migrations.AlterField(
            model_name='user',
            name='touxiang',
            field=models.ImageField(blank=True, default='touxiang/user.png', max_length=64, null=True, upload_to='touxiang/%Y/%m', verbose_name='头像'),
        ),
    ]
