# Generated by Django 3.2.14 on 2022-09-25 06:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0016_auto_20220925_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
    ]
