# Generated by Django 4.2 on 2023-08-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100, verbose_name="用户名")),
                (
                    "email",
                    models.EmailField(max_length=100, unique=True, verbose_name="邮箱"),
                ),
                ("detail", models.TextField(default="", verbose_name="个人简介")),
                (
                    "deleteTaskPower",
                    models.BooleanField(default=False, verbose_name="删除帖子的权限"),
                ),
                (
                    "deleteCommentPower",
                    models.BooleanField(default=False, verbose_name="删除帖子的权限"),
                ),
                (
                    "lookUseerDetailPower",
                    models.BooleanField(default=False, verbose_name="查看其他用户详情页的权限"),
                ),
                (
                    "sendMessagePower",
                    models.BooleanField(default=False, verbose_name="发送消息的权限"),
                ),
            ],
            options={"db_table": "QUser",},
        ),
    ]
