# Generated by Django 4.2 on 2023-08-20 10:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("shoppingapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quser",
            name="create_time",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="注册时间",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quser",
            name="ip",
            field=models.CharField(default="", max_length=18, verbose_name="用户IP地址"),
        ),
        migrations.AddField(
            model_name="quser",
            name="latest_edit",
            field=models.DateTimeField(auto_now=True, verbose_name="最近编辑时间"),
        ),
    ]
